[build]
builder = "railpack"

[build.config]
pkgs = ["openjdk8"]
buildCmd = "./gradlew globalServerShadow --no-daemon -x test"

[deploy]
startCmd = "java -jar **/build/libs/globalServerJar.jar"

[[deploy.ports]]
port = 23762