[build]
builder = "nixpacks"

[build.config]
pkgs = ["openjdk8", "gradle"]

buildCmd = "gradle roomServerShadow --no-daemon -x test"

[deploy]
startCmd = "java -jar **/build/libs/globalServerJar.jar"

[[deploy.ports]]
port = 23762