# Game (client) configuration
# defaultName - suggested player name for dialogs
defaultName=Player
# serversFile - path to servers list (overrides global_servers.txt lookup)
#serversFile=global_servers.txt
